name: ESLint Review
on:
   push:
    paths:
    - '**.js'

jobs: 
  run:
    name: Review with ESLint
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]') && toJSON(github.event.commits.*.message) != '[ESLint] Auto formatting.'"
    steps:
      - uses: actions/checkout@v1
      - name: Install ESLint
        run: npm install --no-package-lock --no-save eslint
      - name: Check Code
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: '.'
          fail_on_error: true
          filter_mode: file