name: ESLint
on:
  push:
    paths:
      - "**.js"
  pull_request:

jobs:
  fix:
    name: Fix code [Push]
    if: "github.event == 'push' || ! contains(toJSON(github.event.commits.*.message), '[SKIP-CI]') && toJSON(github.event.commits.*.message) != '[ESLint] Auto formatting.'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run ESLint
        run: npx eslint . --fix

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: "[ESLint] Auto formatting."
          add: "*.js"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check:
    name: Check code [PR]
    needs: setup
    runs-on: ubuntu-latest
    if: "github.event == 'pull_request'"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run ESLint
        run: npx eslint .